name: CI/CD Pipeline for project App

on:
  push:
    branches:
      - '**'  # Trigger for all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the latest code
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install bandit
      - name: Run Bandit
        run: |
          bandit -r project

   
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Load environment variables
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: |
          echo "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" >> .env
          echo "MYSQL_DATABASE=${MYSQL_DATABASE}" >> .env
          echo "MYSQL_USER=${MYSQL_USER}" >> .env
          echo "MYSQL_PASSWORD=${MYSQL_PASSWORD}" >> .env

      - name: Navigate to project directory
        run: cd project

      - name: Bring down existing containers
        run: docker-compose down -v || true

      - name: Build and start containers
        run: docker-compose up --build -d
      

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker Image
      - name: Build Docker Image
        run: |
          IMAGE_NAME=moshelederman/project-stars
          BUILD_NUMBER=${{ github.run_number }}
          docker build -f project/Dockerfile -t $IMAGE_NAME:latest -t $IMAGE_NAME:0.0.$BUILD_NUMBER .

      # Step 4: Push the Docker Image (only for main branch)
      - name: Push Docker Image
        if: github.ref == 'refs/heads/main'
        run: |
          IMAGE_NAME=moshelederman/project-stars
          BUILD_NUMBER=${{ github.run_number }}
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:0.0.$BUILD_NUMBER

  create-pr:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Create a Pull Request to main
      - name: Create Pull Request to Main
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ${{ github.ref_name }}
          base: main
          title: "Merge ${{ github.ref_name }} to main"
          body: "This pull request merges branch `${{ github.ref_name }}` into the `main` branch."
